#ifndef CONTROLSYMBOLS_H_
#define CONTROLSYMBOLS_H_
#include <string>



const string envGenSymbol("{\"abbr\":\"env\",\"name\":\"Envelope Generator\",\"conParamArray\":[{\"index\":0,\"name\":\"attack\",\"alias\":\"attack\",\"label\":\"Attack\",\"abbr\":\"atk\",\"paramType\":6,\"value\":0,\"inheritControlledParamType\":false,\"controlledParamType\":0,\"controlVoltageEnabled\":false},{\"index\":1,\"name\":\"decay\",\"alias\":\"decay\",\"label\":\"Decay\",\"abbr\":\"dcy\",\"paramType\":6,\"value\":0,\"inheritControlledParamType\":false,\"controlledParamType\":0,\"controlVoltageEnabled\":false},{\"index\":2,\"name\":\"release\",\"alias\":\"release\",\"label\":\"Release\",\"abbr\":\"rls\",\"paramType\":6,\"value\":0,\"inheritControlledParamType\":false,\"controlledParamType\":0,\"controlVoltageEnabled\":false}],\"outputArray\":[{\"index\":0,\"name\":\"output\",\"x\":10,\"y\":-25},{\"index\":1,\"name\":\"outputInv\",\"x\":40,\"y\":-25}],\"symbol\":{\"location\":{\"x\":50,\"y\":50},\"body\":[\"M 10,-5 L 10,-25\",\"M 40,-5 L 40,-25\",\"0,0 25,-15 50,0 50,50 0,50\"],\"graphic\":[\"M 10,10 L 10,40 L 40,40\",\"M 12,38 L 24,18 L 38,38\"],\"color\":\"blue\"}}");
const string lfoSymbol("{\"abbr\":\"lfo\",\"name\":\"Low Frequency Oscillator\",\"conParamArray\":[{\"index\":0,\"name\":\"frequency\",\"alias\":\"frequency\",\"label\":\"Frequency\",\"abbr\":\"freq\",\"paramType\":7,\"value\":0,\"inheritControlledParamType\":false,\"controlledParamType\":0,\"controlVoltageEnabled\":false},{\"index\":1,\"name\":\"amplitude\",\"alias\":\"amplitude\",\"label\":\"Amplitude\",\"abbr\":\"amp\",\"paramType\":8,\"value\":0,\"inheritControlledParamType\":true,\"controlledParamType\":0,\"controlVoltageEnabled\":false},{\"index\":2,\"name\":\"offset\",\"alias\":\"offset\",\"label\":\"Offset\",\"abbr\":\"off\",\"paramType\":9,\"value\":0,\"inheritControlledParamType\":true,\"controlledParamType\":0,\"controlVoltageEnabled\":false}],\"outputArray\":[{\"index\":0,\"name\":\"output\",\"x\":10,\"y\":-25},{\"index\":1,\"name\":\"outputInv\",\"x\":40,\"y\":-25}],\"symbol\":{\"location\":{\"x\":50,\"y\":50},\"body\":[\"M 10,-5 L 10,-25\",\"M 40,-5 L 40,-25\",\"0,0 25,-15 50,0 50,50 0,50\"],\"graphic\":[\"M 8,12 L 8,38\",\"M 8,26 L 46,26\",\"M 8,26 C 23,-10 30,62 46,26\"],\"color\":\"blue\"}}");
const string normSymbol("{\"abbr\":\"norm\",\"name\":\"Normal\",\"conParamArray\":[{\"index\":0,\"name\":\"parameter\",\"alias\":\"parameter\",\"label\":\"Parameter\",\"abbr\":\"prm\",\"paramType\":0,\"value\":0,\"inheritControlledParamType\":true,\"controlledParamType\":0,\"controlVoltageEnabled\":false}],\"outputArray\":[{\"index\":0,\"name\":\"output\",\"x\":10,\"y\":-25},{\"index\":1,\"name\":\"outputInv\",\"x\":40,\"y\":-25}],\"symbol\":{\"location\":{\"x\":50,\"y\":50},\"body\":[\"M 10,-5 L 10,-25\",\"M 40,-5 L 40,-25\",\"0,0 25,-15 50,0 50,50 0,50\"],\"graphic\":[\"M 15,25 A 10,10 0 0,0 35,25 M 15,25 A 10,10 0 1,1 35,25\",\"M 25,25 L 15,35\"],\"color\":\"blue\"}}");



#endif
